server:
  port: 8091
spring:
  application:
    name: dubbo-demo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    subscribed-services: dubbo-demo-provider

# Dubbo 配置项，对应 DubboConfigurationProperties 类
dubbo:
  scan:
    base-packages: com.example.api
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: dubbo-demo-provider
#dubbo:
#  scan:
#    base-packages: com.example.api
#  # Dubbo 服务注册中心配置，对应 RegistryConfig 类
  registry:
    address: spring-cloud://127.0.0.1:8848 # 指定 Dubbo 服务注册中心的地址
#  # Spring Cloud Alibaba Dubbo 专属配置项，对应 DubboCloudProperties 类