server:
  port: 8090
nacos:
  port: 8848
  service-address: 127.0.0.1
  namespace: 06bba7ee-604e-4eb9-baf0-0c71ef4a08d7
spring:
  application:
    name: dubbo-demo-provider
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.service-address}:${nacos.port} #nacos注册地址
dubbo:
  scan:
    base-packages: com.example.api
  protocol:
    name: dubbo
    port: -1
    host: 127.0.0.1
